//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkteraRobotics.ExcelActivities.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkteraRobotics.ExcelActivities.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity closes target workbook. Created by Linktera Robotics..
        /// </summary>
        public static string CloseWorkbook_Description {
            get {
                return ResourceManager.GetString("CloseWorkbook_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Workbook.
        /// </summary>
        public static string CloseWorkbook_DisplayName {
            get {
                return ResourceManager.GetString("CloseWorkbook_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CloseWorkbook_Path_Description {
            get {
                return ResourceManager.GetString("CloseWorkbook_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string CloseWorkbook_Path_DisplayName {
            get {
                return ResourceManager.GetString("CloseWorkbook_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CloseWorkbook_Sheetname_Description {
            get {
                return ResourceManager.GetString("CloseWorkbook_Sheetname_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheetname.
        /// </summary>
        public static string CloseWorkbook_Sheetname_DisplayName {
            get {
                return ResourceManager.GetString("CloseWorkbook_Sheetname_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity copies the target work sheet and paste the values into a new work sheet without any format..
        /// </summary>
        public static string CopySheet_Description {
            get {
                return ResourceManager.GetString("CopySheet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Sheet.
        /// </summary>
        public static string CopySheet_DisplayName {
            get {
                return ResourceManager.GetString("CopySheet_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CopySheet_Path_Description {
            get {
                return ResourceManager.GetString("CopySheet_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string CopySheet_Path_DisplayName {
            get {
                return ResourceManager.GetString("CopySheet_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CopySheet_Sheetname_Description {
            get {
                return ResourceManager.GetString("CopySheet_Sheetname_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheetname.
        /// </summary>
        public static string CopySheet_Sheetname_DisplayName {
            get {
                return ResourceManager.GetString("CopySheet_Sheetname_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activty is created to read huge Excel data and export it into a data table. Activity has not any range property, it reads entire sheet. Created by Linktera Robotics..
        /// </summary>
        public static string ReadBigData_Description {
            get {
                return ResourceManager.GetString("ReadBigData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Big Data.
        /// </summary>
        public static string ReadBigData_DisplayName {
            get {
                return ResourceManager.GetString("ReadBigData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReadBigData_OutData_Description {
            get {
                return ResourceManager.GetString("ReadBigData_OutData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutData.
        /// </summary>
        public static string ReadBigData_OutData_DisplayName {
            get {
                return ResourceManager.GetString("ReadBigData_OutData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReadBigData_Path_Description {
            get {
                return ResourceManager.GetString("ReadBigData_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ReadBigData_Path_DisplayName {
            get {
                return ResourceManager.GetString("ReadBigData_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReadBigData_Sheetname_Description {
            get {
                return ResourceManager.GetString("ReadBigData_Sheetname_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheetname.
        /// </summary>
        public static string ReadBigData_Sheetname_DisplayName {
            get {
                return ResourceManager.GetString("ReadBigData_Sheetname_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReadCell_Cell_Description {
            get {
                return ResourceManager.GetString("ReadCell_Cell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string ReadCell_Cell_DisplayName {
            get {
                return ResourceManager.GetString("ReadCell_Cell_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity read specific cell from target workbook. Created by Linktera Robotics..
        /// </summary>
        public static string ReadCell_Description {
            get {
                return ResourceManager.GetString("ReadCell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Cell.
        /// </summary>
        public static string ReadCell_DisplayName {
            get {
                return ResourceManager.GetString("ReadCell_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReadCell_OutData_Description {
            get {
                return ResourceManager.GetString("ReadCell_OutData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutData.
        /// </summary>
        public static string ReadCell_OutData_DisplayName {
            get {
                return ResourceManager.GetString("ReadCell_OutData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReadCell_Path_Description {
            get {
                return ResourceManager.GetString("ReadCell_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ReadCell_Path_DisplayName {
            get {
                return ResourceManager.GetString("ReadCell_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReadCell_Sheetname_Description {
            get {
                return ResourceManager.GetString("ReadCell_Sheetname_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheetname.
        /// </summary>
        public static string ReadCell_Sheetname_DisplayName {
            get {
                return ResourceManager.GetString("ReadCell_Sheetname_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WriteCell_Cell_Description {
            get {
                return ResourceManager.GetString("WriteCell_Cell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string WriteCell_Cell_DisplayName {
            get {
                return ResourceManager.GetString("WriteCell_Cell_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity writes the value taken from user into a specific cell. Created by Linktera Robotics..
        /// </summary>
        public static string WriteCell_Description {
            get {
                return ResourceManager.GetString("WriteCell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Cell.
        /// </summary>
        public static string WriteCell_DisplayName {
            get {
                return ResourceManager.GetString("WriteCell_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WriteCell_Path_Description {
            get {
                return ResourceManager.GetString("WriteCell_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string WriteCell_Path_DisplayName {
            get {
                return ResourceManager.GetString("WriteCell_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WriteCell_Sheetname_Description {
            get {
                return ResourceManager.GetString("WriteCell_Sheetname_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheetname.
        /// </summary>
        public static string WriteCell_Sheetname_DisplayName {
            get {
                return ResourceManager.GetString("WriteCell_Sheetname_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WriteCell_Value_Description {
            get {
                return ResourceManager.GetString("WriteCell_Value_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string WriteCell_Value_DisplayName {
            get {
                return ResourceManager.GetString("WriteCell_Value_DisplayName", resourceCulture);
            }
        }
    }
}
